In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

In [10]:
path = Path(r"C:\Users\piede\OneDrive\Dokumente\Code\Shiny\ShinyDashboard\raw\OCED_simplified.csv")

In [11]:
df = pd.read_csv(path)

In [12]:
df

,year,country,Immunisation: Hepatitis B_% of children immunised,Immunisation: Influenza_% of population aged 65 years and over,"Immunisation: Diphtheria, Tetanus, Pertussis_% of children immunised",Immunisation: Measles_% of children immunised,Dentists consultations (in all settings)_Number per capita,Doctors consultations (in all settings)_Number per capita,"Computed Tomography exams, total_Number","Computed Tomography exams, total_Per 1 000 population",...,Hysterectomy_Waiting times of patients on the list: Mean (days),Prostatectomy_Waiting times of patients on the list: Median (days),Hysterectomy_Waiting times of patients on the list: Median (days),Prostatectomy_Waiting times of patients on the list: % of all patients waiting more than 3 months,"Colorectal cancer screening, programme data_% of population aged 50-74 screened","Colorectal cancer screening, survey data_% of population aged 50-74 screened","Colorectal cancer screening, programme data_% of females aged 50-74 screened","Colorectal cancer screening, survey data_% of males aged 50-74 screened","Colorectal cancer screening, survey data_% of females aged 50-74 screened","Colorectal cancer screening, programme data_% of males aged 50-74 screened"
0,2010,Australia,91.6,NaN,92.0,93.9,1.5,6.5,2061214.0,93.6,...,NaN,NaN,NaN,NaN,41.0,NaN,44.2,NaN,NaN,37.9
1,2011,Australia,91.6,NaN,92.0,94.0,NaN,6.5,2037101.0,91.2,...,NaN,NaN,NaN,NaN,38.6,NaN,41.6,NaN,NaN,35.7
2,2012,Australia,91.8,NaN,92.2,94.4,NaN,6.5,2365597.0,104.1,...,NaN,NaN,NaN,NaN,37.0,NaN,39.9,NaN,NaN,34.1
3,2013,Australia,91.0,NaN,91.4,93.7,NaN,6.5,2540546.0,109.8,...,NaN,NaN,NaN,NaN,36.1,NaN,38.8,NaN,NaN,33.4
4,2014,Australia,91.2,NaN,91.6,94.4,1.0,6.7,2709088.0,115.4,...,NaN,NaN,NaN,NaN,37.4,NaN,40.1,NaN,NaN,34.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,2018,Colombia,92.0,NaN,92.0,95.0,0.3,2.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
515,2019,Colombia,94.0,NaN,94.0,95.0,0.3,2.6,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,2020,Colombia,87.9,NaN,87.9,90.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,2021,Colombia,87.9,NaN,86.5,86.4,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,2021,Costa Rica,87.4,60.6,92.2,88.8,NaN,NaN,NaN,NaN,...,338.0,627.0,231.0,88.3,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
len(df.columns)

718

In [17]:
df[['year', 'country', 'Crohn\'s disease and ulcerative colitis_Per 100 000 population']]

,year,country,Crohn's disease and ulcerative colitis_Per 100 000 population
0,2010,Australia,30.6
1,2011,Australia,30.9
2,2012,Australia,32.3
3,2013,Australia,34.0
4,2014,Australia,33.7
...,...,...,...
514,2018,Colombia,NaN
515,2019,Colombia,NaN
516,2020,Colombia,NaN
517,2021,Colombia,NaN
518,2021,Costa Rica,NaN